import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { MenuSettings } from "./settings/_components/MenuSettings";
import { IntersectionObserverContextProvider } from "@/components/IntersectionObserverContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <IntersectionObserverContextProvider>
          <div className={clsx("flex flex-row items-start justify-between")}>
            <div
              className={clsx(
                "flex flex-col justify-start max-w-[300px] min-w-[200px] border-r border-r-border h-dvh",
                "sticky top-0",
              )}
            >
              <MenuSettings />
            </div>
            <div className={clsx("flex-1")}>{children}</div>
          </div>
          <div className={clsx("border-t border-t-border p-5 h-[500px]")}>
            footer
          </div>
        </IntersectionObserverContextProvider>
      </body>
    </html>
  );
}
