import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { SideMenu } from "./_compoments/SideMenu";
import { SearchBar } from "./_compoments/SearchBar";
import { PopupMenuButton } from "./_compoments/PopupMenuButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={clsx("grid grid-areas-")}></div>
        <header
          className={clsx(
            "h-[70px]",
            "grid grid-cols-[1fr_auto_1fr] items-center",
            "px-6 py-0",
          )}
        >
          <div>ロゴ</div>
          <SearchBar className={clsx("w-[300px]")} />
          <div className={clsx("flex flex-row items-center justify-end gap-4")}>
            <PopupMenuButton />
            <button
              className={clsx(
                "bg-sky-500 rounded-sm font-bold text-sm text-white px-3 py-1.5 cursor-pointer hover:brightness-90",
              )}
            >
              ログイン
            </button>
          </div>
        </header>
        <div className={clsx("flex flex-row items-start justify-between")}>
          <aside className={clsx("h-dvh border-r border-r-gray-300 pr-2")}>
            <SideMenu />
          </aside>
          {children}
        </div>
        <footer></footer>
      </body>
    </html>
  );
}
