import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { SideMenu } from "./_compoments/SideMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header></header>
        <div className={clsx("flex flex-row items-start justify-between")}>
          <aside className={clsx("h-dvh border-r border-r-gray-300 pr-2")}>
            <SideMenu />
          </aside>
          {children}
        </div>
        <footer></footer>
      </body>
    </html>
  );
}
