import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { MenuLeft } from "./_components/MenuLeft";
import { RightMenu } from "./_components/RightMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          "flex flex-row items-start justify-between gap-4",
          "max-w-[1200px] mx-auto h-dvh",
        )}
      >
        <header className={clsx("w-[250px] p-4 h-dvh")}>
          <MenuLeft />
        </header>
        <div className={clsx("w-[600px] min-w-0 border-x border-x-gray-700")}>
          {children}
        </div>
        <div className={clsx("flex-1 min-w-0")}>
          <RightMenu />
        </div>
      </body>
    </html>
  );
}
